export enum FormCodes {
  ContactForm = "ContactForm",
  MaterialsCommunicationsTMForm = "MaterialsCommunicationsTMForm",
  MaterialsDesignTMForm = "MaterialsDesignTMForm",
  MaterialsLogoUseForm = "MaterialsLogoUseForm",
  MaterialsBrandGuidelinesForm = "MaterialsBrandGuidelinesForm",
  MaterialsMarketingTMForm = "MaterialsMarketingTMForm",
  ProductContactForm = "ProductContactForm",
  ProductQuotationForm = "ProductQuotationForm",
  RMSContactForm = "RMSContactForm",
  RMSQuizForm = "RMSQuizForm",
  ShareYourSolutionForm = "ShareYourSolutionForm",
  SubscribeForm = "SubscribeForm",
  NewsletterForm = "NewsletterForm",
  SupportPageForm = "SupportPageForm",
  VulnerabilityReportForm = "VulnerabilityReportForm",
  WebinarForm = "WebinarForm",
  FileDownloadForm = "FileDownloadForm",
}
